name: Create Cypress report
on:
  push:
    branches:
      - 'master'

jobs:
  
  install:
    name: Install all dependencies
    runs-on: ubuntu-18.04
    container: cypress/base:10
    steps:
      - uses: actions/checkout@v2
      - name: Install a project with a clean slate
        run: npm ci
      - run: $(npm bin)/cypress cache path
      - run: $(npm bin)/cypress cache list
      - run: $(npm bin)/cypress verify
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            .npm
            cache/Cypress
            node_modules
          key: ${{ runner.os }}-cypress

  cypress-e2e:
    name: Run E2E tests on Electron browser
    runs-on: ubuntu-18.04
    container: cypress/base:10
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - name: Run E2E tests
        run: npm run test

