name: Create Cypress report
on:
  push:
    branches:
      - 'master'

jobs:
  
  cypress-e2e:
    name: Run Cypress tests in Chrome 67
    runs-on: ubuntu-18.04
    container: cypress/browsers:chrome67
    steps:
      - uses: actions/checkout@v2
      - name: Install a project with a clean slate
        run: |
          npm ci
          $(npm bin)/cypress cache path
          $(npm bin)/cypress cache list
          $(npm bin)/cypress verify
      - name: Run E2E tests
        run: npm run test:chrome
        continue-on-error: true
      - name: Copy resulting screenshots & videos
        run: cp -r cypress/videos public/videos
      - name: Merge test results into one
        run: npm run report:merge
      - name: Generate HTML report
        run: npm run report:generate


